#!/usr/bin/perl -w

use strict;

use warnings;


our $global_configuration;


package Command;


my $color_help = '
https://linux.101hacks.com/ps1-examples/prompt-color-using-tput/

tput Color Capabilities:

    tput setab [1-7] – Set a background color using ANSI escape
    tput setb [1-7] – Set a background color
    tput setaf [1-7] – Set a foreground color using ANSI escape
    tput setf [1-7] – Set a foreground color

tput Text Mode Capabilities:

    tput bold – Set bold mode
    tput dim – turn on half-bright mode
    tput smul – begin underline mode
    tput rmul – exit underline mode
    tput rev – Turn on reverse mode
    tput smso – Enter standout mode (bold on rxvt)
    tput rmso – Exit standout mode
    tput sgr0 – Turn off all attributes

Color Code for tput:

black=$(tput setaf 0)
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
magenta=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)

# give IP addresses prefixed with "addr:" a yellow color:

$ project-workflow ip_routing all | sed -E "s|addr:([0-9]+.[0-9]+.[0-9]+.[0-9]+)|addr:${yellow}\1${white}|g"
';


sub heccer_test_command
{
    my $filename = "ls.sh";

    execute_shell_script
	(
	 $filename,
	 {
	  remote => {
		     description => "for testing",
		     name => "virtual-remote",
		     ssh_options => "-o LogLevel=ERROR -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null",
		     ssh_password => "root",
		     ssh_port => "22",
		     ssh_server => "192.168.0.210",
		     ssh_user => "root",
		    },
	 },
	);
}


sub heccer_build_manual
{
    my $commands
	= [
	   "cd $ENV{HOME}/projects/heccer/source/snapshots/master",
	   "neurospaces_harness --tags manual --output-pdf --output-figures --verbose",
	  ];

    my $build_tree
	= {
	   sources => [
		       "$ENV{HOME}/projects/heccer/source/snapshots/master/tests/specifications/version.t",
		      ],
	   targets => [
		       "/tmp/report_heccer.yml",
		       "/tmp/test_report_heccer",
		       "/tmp/test_report_heccer/",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module2_perfectclamp__t_3_tests___code___perfectclamp-passive10-2_1_NONE-perfectclamp_output_graph_render_figure_definition.yml",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module2_perfectclamp__t_3_tests___code___perfectclamp-passive10-2_1_NONE-perfectclamp_output_graph_render_data",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module/figures",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module/figures/ns-main-logo-dark2.jpg",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module3_pulsegen__t_1_tests___code___pulsegen-freerun_1_NONE-pulsegen_output_graph_render_figure_definition.yml",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module3_pulsegen__t_1_tests___code___pulsegen-freerun_1_NONE-pulsegen_output_graph_render_data",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module.aux",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module1_active___hh__t_1_tests___code___hh1_1_NONE-hh_output_graph_render_data",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module2_perfectclamp__t_2_tests___code___perfectclamp-passive10_1_NONE-perfectclamp_output_graph_render_data",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module3_pulsegen__t_2_tests___code___pulsegen-extgate_1_NONE-pulsegen_output_graph_render_data",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module3_pulsegen__t_2_tests___code___pulsegen-extgate_1_NONE-pulsegen-output_graph_render.png",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module2_perfectclamp__t_2_tests___code___perfectclamp-passive10_1_NONE-perfectclamp-output_graph_render.png",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module3_pulsegen__t_2_tests___code___pulsegen-extgate_1_NONE-pulsegen_output_graph_render_figure_definition.yml",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module2_perfectclamp__t_2_tests___code___perfectclamp-passive10_1_NONE-perfectclamp_output_graph_render_figure_definition.yml",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module3_pulsegen__t_3_tests___code___pulsegen-exttrig_1_NONE-pulsegen-output_graph_render.png",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module3_pulsegen__t_1_tests___code___pulsegen-freerun_1_NONE-pulsegen-output_graph_render.png",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module.tex",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module1_active___hh__t_1_tests___code___hh1_1_NONE-hh_output_graph_render_figure_definition.yml",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module.out",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module.log",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module.pdf",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module2_perfectclamp__t_1_tests___code___perfectclamp-passive1_1_NONE-perfectclamp_output_graph_render_data",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module3_pulsegen__t_3_tests___code___pulsegen-exttrig_1_NONE-pulsegen_output_graph_render_figure_definition.yml",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module3_pulsegen__t_3_tests___code___pulsegen-exttrig_1_NONE-pulsegen_output_graph_render_data",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module2_perfectclamp__t_1_tests___code___perfectclamp-passive1_1_NONE-perfectclamp-output_graph_render.png",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module1_active___hh__t_1_tests___code___hh1_1_NONE-hh-output_graph_render.png",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module2_perfectclamp__t_3_tests___code___perfectclamp-passive10-2_1_NONE-perfectclamp-output_graph_render.png",
		       "/tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module2_perfectclamp__t_1_tests___code___perfectclamp-passive1_1_NONE-perfectclamp_output_graph_render_figure_definition.yml",
		      ],
	  };

    execute_shell_command_array($commands, { build_tree => $build_tree, }, );
}


sub heccer_build_manual_visual
{
    heccer_build_manual();

    heccer_manual_visual();
}


sub heccer_manual_visual
{
    my $commands
	= [
	   "okular /tmp/test_report_heccer/test_report_heccer_command_definition-command_test-meta-module.pdf &",
	  ];

    execute_shell_command_array($commands);
}


sub ip_routing_all
{
    ip_routing_developer_laptop();
}


our $option_bash_completion;

our $command_options
    = {
       "bash-completion=s" => \$option_bash_completion,
      };

sub ip_routing_developer_laptop
{
    use Getopt::Long qw(GetOptionsFromArray);

    my $arguments = shift || [];

    my $result = GetOptionsFromArray($arguments, %$command_options);

    use Data::Dumper;

    print Dumper($arguments, $command_options, $option_bash_completion);

    my $commands
	= [
	   "netstat -rn",
	  ];

    execute_shell_command_array($commands);
}


sub ssp_build_manual
{
    my $commands
	= [
	   "cd $ENV{HOME}/projects/ssp/source/snapshots/master",
	   "neurospaces_harness --tags manual --output-pdf --output-figures --verbose",
	  ];

    my $build_tree
	= {
	   sources => [
		       "$ENV{HOME}/projects/ssp/source/snapshots/master/tests/specifications/0_startup.t",
		      ],
	   targets => [
		       "/tmp/report_ssp.yml",
		       "/tmp/test_report_ssp",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module1_builtins___purkinje__t_2_bin___ssp_1_NONE-hh-vm_output_graph_render_figure_definition.yml",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module3_integration___tabulator__t_4_tests___perl___hh_tabulator_alpha_beta_1_NONE-hh-vm-b-forward-output_graph_render.png",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module3_integration___tabulator__t_4_tests___perl___hh_tabulator_alpha_beta_1_NONE-hh-vm-b-backward-output_graph_render.png",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module2_integration___purkinje__t_2_bin___ssp_1_NONE-hh-vm-output_graph_render.png",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module.aux",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module2_integration___purkinje__t_2_bin___ssp_1_NONE-hh-vm_output_graph_render_data",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module3_integration___tabulator__t_1_tests___perl___hh_tabulator_internal_1_NONE-hh-vm-a-output_graph_render.png",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module1_builtins___purkinje__t_3_bin___ssp_1_NONE-hh-vm_output_graph_render_data",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module1_builtins___purkinje__t_1_bin___ssp_1_NONE-hh-vm_output_graph_render_figure_definition.yml",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module1_builtins___purkinje__t_3_bin___ssp_1_NONE-hh-vm-output_graph_render.png",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module2_integration___purkinje__t_2_bin___ssp_1_NONE-hh-vm_output_graph_render_figure_definition.yml",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module.log",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module.tex",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module2_integration___purkinje__t_2_bin___ssp_1_NONE-hh-ca_output_graph_render_data",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module.out",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module2_integration___purkinje__t_2_bin___ssp_1_NONE-hh-ca-output_graph_render.png",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module1_builtins___purkinje__t_1_bin___ssp_1_NONE-hh-vm-output_graph_render.png",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module3_integration___tabulator__t_1_tests___perl___hh_tabulator_internal_1_NONE-hh-vm-b-output_graph_render.png",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module1_builtins___purkinje__t_3_bin___ssp_1_NONE-hh-vm_output_graph_render_figure_definition.yml",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module2_integration___purkinje__t_2_bin___ssp_1_NONE-hh-ca_output_graph_render_figure_definition.yml",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module3_integration___tabulator__t_1_tests___perl___hh_tabulator_internal_1_NONE-hh-vm_output_graph_render_data",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module3_integration___tabulator__t_4_tests___perl___hh_tabulator_alpha_beta_1_NONE-hh-vm_output_graph_render_data",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module/figures",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module/figures/ns-main-logo-dark2.jpg",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module1_builtins___purkinje__t_2_bin___ssp_1_NONE-hh-vm_output_graph_render_data",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module1_builtins___purkinje__t_2_bin___ssp_1_NONE-hh-vm-output_graph_render.png",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module3_integration___tabulator__t_4_tests___perl___hh_tabulator_alpha_beta_1_NONE-hh-vm_output_graph_render_figure_definition.yml",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module1_builtins___purkinje__t_1_bin___ssp_1_NONE-hh-vm_output_graph_render_data",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module3_integration___tabulator__t_4_tests___perl___hh_tabulator_alpha_beta_1_NONE-hh-vm-a-forward-output_graph_render.png",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module3_integration___tabulator__t_1_tests___perl___hh_tabulator_internal_1_NONE-hh-vm_output_graph_render_figure_definition.yml",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module.pdf",
		       "/tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module3_integration___tabulator__t_4_tests___perl___hh_tabulator_alpha_beta_1_NONE-hh-vm-a-backward-output_graph_render.png",
		      ],
	  };

    execute_shell_command_array($commands, { build_tree => $build_tree, }, );
}


sub ssp_build_manual_visual
{
    ssp_build_manual();

    ssp_manual_visual();
}


sub ssp_manual_visual
{
    my $commands
	= [
	   "okular /tmp/test_report_ssp/test_report_ssp_command_definition-command_test-meta-module.pdf &",
	  ];

    execute_shell_command_array($commands);
}


($0 =~ m(.*/(\S+)));

my $program_name = $1;


if ($program_name =~ m'commands$')
{
    # could possibly do something sensible with Devel::Symdump here

    # choose one of 'Data::Dumper', 'yaml', 'json', 'json_pretty'

    my $output_format = 'default';

    if ($output_format eq 'yaml')
    {
	require YAML;

	# print YAML::Dump($configuration);
    }
    elsif ($output_format eq 'json')
    {
	require JSON;

        my $json = JSON->new(); # ->allow_nonref;

	$json->allow_unknown(1);

	# my $encoded = $json->encode($configuration);

	# print $encoded;
    }
    elsif ($output_format eq 'json_pretty')
    {
	require JSON;

        my $json = JSON->new(); # ->allow_nonref;

	$json->allow_unknown(1);

	# my $encoded = $json->pretty()->encode($configuration);

	# print $encoded;
    }
    else
    {
	require Data::Dumper;

	no warnings;

	$Data::Dumper::Sortkeys = 'always';

	# print Data::Dumper::Dumper($configuration);
    }
}
else
{
    # return $configuration;
}


# return success

1;


