#!/usr/bin/perl -w
#!/usr/bin/perl -d:ptkdb -w
#

use strict;


#
# This is a script for checking the GENESIS3 enviroment to see if Inline Python as
# well as the python imports are working correctly.
#

BEGIN
{
    if (defined $ENV{PYTHONPATH})
    {
	$ENV{PYTHONPATH} .= ":/usr/local/glue/swig/python";
    }
    else
    {
	$ENV{PYTHONPATH} = "/usr/local/glue/swig/python";
    }

    my $os = $^O;

    # Need to figure out how to make inline python call the correct python executable.
    if($os eq "darwin")
    {

      #$ENV{PYTHONEXECUTABLE} = "/Library/Frameworks/Python.framework/Versions/Current/bin/python";

    }

}


use Inline Python => <<'END';
import os
import sys
print "The Inline Python caller is: ",sys.executable
print "The Inline Python caller should be some derivative of perl, since it is being called via the perl Inline::Python module\n"

print "Python version is ",sys.version,"\n"

sys.path.append('/usr/local/glue/swig/python')

print "Python path is: "
print sys.path
print "\nThe Python Path should match up with the proper python version of the executable.\n"


print "This executable path", os.path.dirname(sys.executable)

print "\nPerforming an import check of installed GENESIS3 Python modules:\n"

try:
  import Neurospaces
except ImportError, e:
  print "! The Neurospaces python module is not installed or not in your path.\n"

try:
  import SwiggableNeurospaces
except ImportError, e:
  print "! The SwiggableNeurospaces python module is not installed or not in your path.\n"

try:
  import Heccer
except ImportError, e:
  print "! The Heccer python module is not installed or not in your path.\n"

try:
  import SwiggableHeccer
except ImportError, e:
  print "! The SwiggableHeccer python module is not installed or not in your path.\n"

try:
  import SwiggableExperiment
except ImportError, e:
  print "! The SwiggableExperiment python module is not installed or not in your path.\n"

try:
  import yaml
except ImportError, e:
  print "! The PyYAML python module is not installed or not in your path.\n"
END


sub main
{
  #Just some cleanup. 

  if(-d '_Inline')
  {
    system "rm -rf _Inline";
  }

  print "Done with Python check.\n\n";
}

main();
